<?php

namespace Album\AlbumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumsRepository extends EntityRepository
{
}
